
title: Prasannjeet Singh - My Resume
url: 'http://prasannjeet.github.io'
baseurl: '/' #change it according to your repository name



# Profile information
yourname: Prasannjeet Singh  ## put your name
title: 'GRADUATE STUDENT AT LINNAEUS UNIVERSITY'  ## your title
location: Växjö , Sweden


## Social Profiles
facebook: http://www.facebook.com/9prasannjeet  ## your facebook account url
twitter: http://www.twitter.com/prasannjeet  ## your twitter account url
linkedin: http://www.linkedin.com/in/prasannjeet  ## your linkedin account url
dribbble: http://www.dribble.com  ## you dribbble account url
foursquare: http://www.foursquare.com  ## your foursquare account url



# Update all the sections by editing the files inside _includes folder.
