
title: Prasannjeet Singh - My Resume
url: 'http://prasannjeet.github.io'
baseurl: '/' #change it according to your repository name
highlighter: rouge


# Profile information
yourname: Prasannjeet  ## put your name
title: 'GRADUATE STUDENT AT LINNAEUS UNIVERSITY'  ## your title
location: Växjö , Sweden


## Social Profiles
facebook: http://www.facebook.com/9prasannjeet  ## your facebook account url
twitter: http://www.twitter.com/prasannjeet  ## your twitter account url
linkedin: http://www.linkedin.com/in/prasannjeet  ## your linkedin account url
dribbble: https://www.quora.com/profile/Prasannjeet-Singh  ## you dribbble account url
foursquare: https://github.com/prasannjeet  ## your foursquare account url



# Update all the sections by editing the files inside _includes folder.
